# Generated by Django 5.1.5 on 2025-01-21 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(blank=True, max_length=250, null=True)),
                ('website_description', models.TextField(blank=True, null=True)),
                ('website_keywords', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(upload_to='pageheaders/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg', 'jpeg'])])),
                ('page_title', models.CharField(blank=True, max_length=75, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Page Header',
                'verbose_name_plural': 'Page Headers',
                'ordering': ('id',),
                'managed': True,
            },
        ),
    ]
