# Generated by Django 5.1.5 on 2025-01-22 01:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_resource_alter_homepage_disclaimer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='article',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
