# Generated by Django 5.1.5 on 2025-02-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_homepage_objectives_image_homepage_objectives_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageheader',
            name='page',
            field=models.CharField(choices=[('about', 'ABOUT THE PROJECT'), ('partners', 'PARTNERS'), ('projects', 'PROJECTS'), ('resources', 'RESOURCES'), ('contact', 'CONTACT'), ('impressum', 'IMPRESSUM'), ('privacy', 'PRIVACY POLICY'), ('disclaimer', 'DISCLAIMER')], default='about', max_length=25, verbose_name='Related Page'),
        ),
    ]
