# Generated by Django 5.1.5 on 2025-02-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_pageheader_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
